# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ASUS\programming\qt_programs\chat\chat.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(658, 545)
        MainWindow.setStyleSheet("background-color: rgb(226, 214, 235);\n"
"background-color: rgb(243, 243, 243);\n"
"background-color: rgb(199, 226, 240);\n"
"background-color: rgb(222, 219, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 658, 26))
        self.menubar.setObjectName("menubar")
        self.menu_Chats = QtWidgets.QMenu(self.menubar)
        self.menu_Chats.setObjectName("menu_Chats")
        self.menu_Profile = QtWidgets.QMenu(self.menubar)
        self.menu_Profile.setObjectName("menu_Profile")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Connect = QtWidgets.QAction(MainWindow)
        self.action_Connect.setObjectName("action_Connect")
        self.action_Image = QtWidgets.QAction(MainWindow)
        self.action_Image.setObjectName("action_Image")
        self.action_Username = QtWidgets.QAction(MainWindow)
        self.action_Username.setObjectName("action_Username")
        self.action_Help = QtWidgets.QAction(MainWindow)
        self.action_Help.setObjectName("action_Help")
        self.menu_Chats.addAction(self.action_Connect)
        self.menu_Profile.addAction(self.action_Image)
        self.menu_Profile.addAction(self.action_Username)
        self.menu_About.addAction(self.action_Help)
        self.menubar.addAction(self.menu_Chats.menuAction())
        self.menubar.addAction(self.menu_Profile.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu_Chats.setTitle(_translate("MainWindow", "&Chat"))
        self.menu_Profile.setTitle(_translate("MainWindow", "&Profile"))
        self.menu_About.setTitle(_translate("MainWindow", "&Help"))
        self.action_Connect.setText(_translate("MainWindow", "&Connect"))
        self.action_Image.setText(_translate("MainWindow", "&Image"))
        self.action_Username.setText(_translate("MainWindow", "&Username"))
        self.action_Help.setText(_translate("MainWindow", "&About"))
